language: python
python:
  - "3.6"
install:
  - python -m pip install --upgrade pip
  - pip install -r Sensor/requirements.txt
# command to run tests
script: 
  - python Sensor/test/tests.py


notifications:
  email: false