stages:
- test
- build

services:
  - docker

matrix:
  include:
    - stage: test
      language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r APIGateway/requirements.txt
      script:
        - python APIGateway/gateway/tests.py

    - stage: test
      language: java
      before_install:
        - cd Monitor
      install:
        - mvn clean
        - mvn install
      script:
        - mvn test

    - stage: test
      language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r Sensor/requirements.txt
      script:
        - python Sensor/test/tests.py

    - stage: test
      dist: xenial
      language: node_js
      node_js:
        - "8"
      before_install:
        - cd client
      install:
        - npm install
      script:
        - npm run test

    - stage: build
      dist: xenial
      language: python
      install:
        - python -m pip install --upgrade pip
        - pip install -r tests/requirements.txt
      script:
        - docker build --tag=pz-gr2:gateway-km3 APIGateway/
        - docker build --tag=pz-gr2:monitor-km3 Monitor/
        - docker build --tag=pz-gr2:sensor-km3 Sensor/
        - docker build --tag=pz-gr2:client-km3 client/
      after_success:
        - docker run -d --network host -it pz-gr2:gateway-km3
        - docker run -d --network host -it pz-gr2:monitor-km3
        - docker run -d --network host -it pz-gr2:sensor-km3
        - docker images
      before_deployment:
        - python tests/tests.py



notifications:
  email: false