matrix:
  include:
    - language: python
      python: 3.6
      install:
        - python -m pip install --upgrade pip
        - pip install -r APIGateway/requirements.txt
      script:
        - python APIGateway/APIGateway/tests.py


notifications:
  email: false
