matrix:
  include:
    - stage: test
      language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r APIGateway/requirements.txt
      script:
        - python APIGateway/gateway/tests.py

    - stage: test
      language: java
      before_install:
        - cd Monitor
      install:
        - mvn install
      script:
        - mvn test

    - stage: test
      language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r Sensor/requirements.txt
      script:
        - python Sensor/test/tests.py

    - stage: test
      language: node_js
      before_install:
        - cd client
      install:
        - npm install stable
      script:
        - npm run test


notifications:
  email: false