matrix:
  include:
    - language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r APIGateway/requirements.txt
      script:
        - python APIGateway/gateway/tests.py

    - language: java
      before_install:
        - cd Monitor
      install:
        - mvn install
      before_script:
        - cd Monitor
      script:
        - Monitor/mvn test

    - language: python
      python: 3.7
      dist: xenial
      install:
        - python -m pip install --upgrade pip
        - pip install -r Sensor/requirements.txt
      script:
        - python Sensor/test/tests.py



notifications:
  email: false