matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd APIGateway
      install:
        - python -m pip install --upgrade pip
        - pip install -r requirements.txt
      script:
        - python APIGateway/test.py



notifications:
  email: false