# Generated by Django 2.2 on 2019-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('endpoint', models.TextField()),
            ],
        ),
    ]
